# Generated by Django 5.0.6 on 2024-07-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name': 'Listing'},
        ),
        migrations.AddField(
            model_name='listings',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
