# Generated by Django 5.0.6 on 2024-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0002_alter_listings_options_listings_picture1'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/'),
        ),
    ]
