# Generated by Django 5.0.6 on 2024-07-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0003_listings_picture2_listings_picture3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='tittle',
            new_name='title',
        ),
    ]
