# Generated by Django 5.0.6 on 2024-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0007_alter_listings_area_alter_listings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='area',
            field=models.CharField(blank=True, choices=[('Inner London', 'Inner London'), ('Outer London', 'Outer London')], max_length=50, null=True),
        ),
    ]
