# Generated by Django 5.0.6 on 2024-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0008_alter_listings_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
